language: php

php:
  - 7.2
  - 7.3
  - 7.4

addons:
  code_climate:
    repo_token:
      secure: "BnElzT3JxJpHqIKARA4Fucr0lZaPe1qtx1KN+17jm5pYWm0SnsIFIDg7qx2px1AXGknRHoSLSJ6Cr2Ii5Uxc/UMcr5GoG9HnHLsfFenlWUVbzT+OGbtG+Y0jSY/dilwS422DLcp83Mjg9uzBoLVrIO1fA1d6RMH8qCDC/vxacSzef/Mr7RWdcusw3JFiQpgOt5pdPq13O+S/0OkuQRQMvU9jO22j9ufMxZGn1clJbuu/SkGtnQZiHot+mlo7c11zZR5hpjRp0OmDKBMa+pkERFqqx4oCgrS2WHYnejIkiFX7A2ROhsr4I74aVm2V0cHiL732Iule6uEC2AoZsx8ZLB+KpgWHMHeOYvbdy9SzwuzcY3K5zXybMj8/AwcgKUKWm2HH1uj8GtBi7o7jxzSkiqNCtg0MshthAUmQTnSTLG3rPbBFtf8BKXzVLdZS3kfHmDy4AcQ9ZKRoQiE9XQQEcHqElCNE8nKMxAB4xE9ZRfF/1kZwhFCF76Lq6M3KBFr8Z6LuwmWzivIZ1aajPE3DuDp9Aj+9GNnFfftgFpKDU1P0jF8/0GRsp1UoDU+D9kYISVkAW8Qj3z6sTbfe0AWyWXkvPIBx5HzYuws5TVoCdJbe1HP2fN5kUMZwpPA8XV9xMGQLOz33Wj3EqAg2i7iWcW/HOhFufLE6QTuQ4NIk2Rc="

branches:
  only:
    master

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true

install:
  - travis_retry composer install

script:
  - if [ "$TRAVIS_PHP_VERSION" != "7.3" ]; then composer test; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.3" ]; then composer test-coverage; fi

after_script:
  - vendor/bin/test-reporter